/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResponderRouteImport } from './routes/responder'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as ResponderIndexRouteImport } from './routes/responder.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VendorStorefrontRouteImport } from './routes/vendor.storefront'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorSalesRouteImport } from './routes/vendor.sales'
import { Route as VendorRatingsRouteImport } from './routes/vendor.ratings'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as ResponderDirectoryRouteImport } from './routes/responder.directory'
import { Route as ResponderBroadcastRouteImport } from './routes/responder.broadcast'
import { Route as ResponderAlertsRouteImport } from './routes/responder.alerts'
import { Route as OnboardingVendorRouteImport } from './routes/onboarding.vendor'
import { Route as OnboardingUserRouteImport } from './routes/onboarding.user'
import { Route as OnboardingTransportRouteImport } from './routes/onboarding.transport'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as OnboardingProviderRouteImport } from './routes/onboarding.provider'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding.complete'
import { Route as DriverSettingsRouteImport } from './routes/driver.settings'
import { Route as DriverRequestsRouteImport } from './routes/driver.requests'
import { Route as DriverHistoryRouteImport } from './routes/driver.history'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as DashboardSosRouteImport } from './routes/dashboard.sos'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRideRouteImport } from './routes/dashboard.ride'
import { Route as DashboardFoodRouteImport } from './routes/dashboard.food'
import { Route as DashboardEmergencyRouteImport } from './routes/dashboard.emergency'
import { Route as DashboardFoodIndexRouteImport } from './routes/dashboard.food.index'
import { Route as DashboardFoodTrackRouteImport } from './routes/dashboard.food.track'
import { Route as DashboardFoodCheckoutRouteImport } from './routes/dashboard.food.checkout'
import { Route as DashboardFoodVendorRouteImport } from './routes/dashboard.food.$vendor'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderRoute = ResponderRouteImport.update({
  id: '/responder',
  path: '/responder',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const ResponderIndexRoute = ResponderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResponderRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VendorStorefrontRoute = VendorStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSalesRoute = VendorSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => VendorRoute,
} as any)
const VendorRatingsRoute = VendorRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const ResponderDirectoryRoute = ResponderDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => ResponderRoute,
} as any)
const ResponderBroadcastRoute = ResponderBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => ResponderRoute,
} as any)
const ResponderAlertsRoute = ResponderAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ResponderRoute,
} as any)
const OnboardingVendorRoute = OnboardingVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingUserRoute = OnboardingUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingTransportRoute = OnboardingTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProviderRoute = OnboardingProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRoute,
} as any)
const DriverSettingsRoute = DriverSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverRequestsRoute = DriverRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DashboardSosRoute = DashboardSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRideRoute = DashboardRideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFoodRoute = DashboardFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmergencyRoute = DashboardEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFoodIndexRoute = DashboardFoodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFoodRoute,
} as any)
const DashboardFoodTrackRoute = DashboardFoodTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => DashboardFoodRoute,
} as any)
const DashboardFoodCheckoutRoute = DashboardFoodCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => DashboardFoodRoute,
} as any)
const DashboardFoodVendorRoute = DashboardFoodVendorRouteImport.update({
  id: '/$vendor',
  path: '/$vendor',
  getParentRoute: () => DashboardFoodRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/responder': typeof ResponderRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/food': typeof DashboardFoodRouteWithChildren
  '/dashboard/ride': typeof DashboardRideRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/transport': typeof OnboardingTransportRoute
  '/onboarding/user': typeof OnboardingUserRoute
  '/onboarding/vendor': typeof OnboardingVendorRoute
  '/responder/alerts': typeof ResponderAlertsRoute
  '/responder/broadcast': typeof ResponderBroadcastRoute
  '/responder/directory': typeof ResponderDirectoryRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/ratings': typeof VendorRatingsRoute
  '/vendor/sales': typeof VendorSalesRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/storefront': typeof VendorStorefrontRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/responder/': typeof ResponderIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/dashboard/food/$vendor': typeof DashboardFoodVendorRoute
  '/dashboard/food/checkout': typeof DashboardFoodCheckoutRoute
  '/dashboard/food/track': typeof DashboardFoodTrackRoute
  '/dashboard/food/': typeof DashboardFoodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/ride': typeof DashboardRideRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/transport': typeof OnboardingTransportRoute
  '/onboarding/user': typeof OnboardingUserRoute
  '/onboarding/vendor': typeof OnboardingVendorRoute
  '/responder/alerts': typeof ResponderAlertsRoute
  '/responder/broadcast': typeof ResponderBroadcastRoute
  '/responder/directory': typeof ResponderDirectoryRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/ratings': typeof VendorRatingsRoute
  '/vendor/sales': typeof VendorSalesRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/storefront': typeof VendorStorefrontRoute
  '/dashboard': typeof DashboardIndexRoute
  '/driver': typeof DriverIndexRoute
  '/responder': typeof ResponderIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/dashboard/food/$vendor': typeof DashboardFoodVendorRoute
  '/dashboard/food/checkout': typeof DashboardFoodCheckoutRoute
  '/dashboard/food/track': typeof DashboardFoodTrackRoute
  '/dashboard/food': typeof DashboardFoodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/responder': typeof ResponderRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/food': typeof DashboardFoodRouteWithChildren
  '/dashboard/ride': typeof DashboardRideRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/transport': typeof OnboardingTransportRoute
  '/onboarding/user': typeof OnboardingUserRoute
  '/onboarding/vendor': typeof OnboardingVendorRoute
  '/responder/alerts': typeof ResponderAlertsRoute
  '/responder/broadcast': typeof ResponderBroadcastRoute
  '/responder/directory': typeof ResponderDirectoryRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/ratings': typeof VendorRatingsRoute
  '/vendor/sales': typeof VendorSalesRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/storefront': typeof VendorStorefrontRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/responder/': typeof ResponderIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/dashboard/food/$vendor': typeof DashboardFoodVendorRoute
  '/dashboard/food/checkout': typeof DashboardFoodCheckoutRoute
  '/dashboard/food/track': typeof DashboardFoodTrackRoute
  '/dashboard/food/': typeof DashboardFoodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/driver'
    | '/onboarding'
    | '/responder'
    | '/signin'
    | '/signup'
    | '/vendor'
    | '/dashboard/emergency'
    | '/dashboard/food'
    | '/dashboard/ride'
    | '/dashboard/settings'
    | '/dashboard/sos'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/requests'
    | '/driver/settings'
    | '/onboarding/complete'
    | '/onboarding/provider'
    | '/onboarding/role'
    | '/onboarding/transport'
    | '/onboarding/user'
    | '/onboarding/vendor'
    | '/responder/alerts'
    | '/responder/broadcast'
    | '/responder/directory'
    | '/vendor/products'
    | '/vendor/ratings'
    | '/vendor/sales'
    | '/vendor/settings'
    | '/vendor/storefront'
    | '/dashboard/'
    | '/driver/'
    | '/responder/'
    | '/vendor/'
    | '/dashboard/food/$vendor'
    | '/dashboard/food/checkout'
    | '/dashboard/food/track'
    | '/dashboard/food/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/dashboard/emergency'
    | '/dashboard/ride'
    | '/dashboard/settings'
    | '/dashboard/sos'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/requests'
    | '/driver/settings'
    | '/onboarding/complete'
    | '/onboarding/provider'
    | '/onboarding/role'
    | '/onboarding/transport'
    | '/onboarding/user'
    | '/onboarding/vendor'
    | '/responder/alerts'
    | '/responder/broadcast'
    | '/responder/directory'
    | '/vendor/products'
    | '/vendor/ratings'
    | '/vendor/sales'
    | '/vendor/settings'
    | '/vendor/storefront'
    | '/dashboard'
    | '/driver'
    | '/responder'
    | '/vendor'
    | '/dashboard/food/$vendor'
    | '/dashboard/food/checkout'
    | '/dashboard/food/track'
    | '/dashboard/food'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/driver'
    | '/onboarding'
    | '/responder'
    | '/signin'
    | '/signup'
    | '/vendor'
    | '/dashboard/emergency'
    | '/dashboard/food'
    | '/dashboard/ride'
    | '/dashboard/settings'
    | '/dashboard/sos'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/requests'
    | '/driver/settings'
    | '/onboarding/complete'
    | '/onboarding/provider'
    | '/onboarding/role'
    | '/onboarding/transport'
    | '/onboarding/user'
    | '/onboarding/vendor'
    | '/responder/alerts'
    | '/responder/broadcast'
    | '/responder/directory'
    | '/vendor/products'
    | '/vendor/ratings'
    | '/vendor/sales'
    | '/vendor/settings'
    | '/vendor/storefront'
    | '/dashboard/'
    | '/driver/'
    | '/responder/'
    | '/vendor/'
    | '/dashboard/food/$vendor'
    | '/dashboard/food/checkout'
    | '/dashboard/food/track'
    | '/dashboard/food/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ResponderRoute: typeof ResponderRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VendorRoute: typeof VendorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder': {
      id: '/responder'
      path: '/responder'
      fullPath: '/responder'
      preLoaderRoute: typeof ResponderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/responder/': {
      id: '/responder/'
      path: '/'
      fullPath: '/responder/'
      preLoaderRoute: typeof ResponderIndexRouteImport
      parentRoute: typeof ResponderRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/vendor/storefront': {
      id: '/vendor/storefront'
      path: '/storefront'
      fullPath: '/vendor/storefront'
      preLoaderRoute: typeof VendorStorefrontRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/sales': {
      id: '/vendor/sales'
      path: '/sales'
      fullPath: '/vendor/sales'
      preLoaderRoute: typeof VendorSalesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/ratings': {
      id: '/vendor/ratings'
      path: '/ratings'
      fullPath: '/vendor/ratings'
      preLoaderRoute: typeof VendorRatingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/responder/directory': {
      id: '/responder/directory'
      path: '/directory'
      fullPath: '/responder/directory'
      preLoaderRoute: typeof ResponderDirectoryRouteImport
      parentRoute: typeof ResponderRoute
    }
    '/responder/broadcast': {
      id: '/responder/broadcast'
      path: '/broadcast'
      fullPath: '/responder/broadcast'
      preLoaderRoute: typeof ResponderBroadcastRouteImport
      parentRoute: typeof ResponderRoute
    }
    '/responder/alerts': {
      id: '/responder/alerts'
      path: '/alerts'
      fullPath: '/responder/alerts'
      preLoaderRoute: typeof ResponderAlertsRouteImport
      parentRoute: typeof ResponderRoute
    }
    '/onboarding/vendor': {
      id: '/onboarding/vendor'
      path: '/vendor'
      fullPath: '/onboarding/vendor'
      preLoaderRoute: typeof OnboardingVendorRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/user': {
      id: '/onboarding/user'
      path: '/user'
      fullPath: '/onboarding/user'
      preLoaderRoute: typeof OnboardingUserRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/transport': {
      id: '/onboarding/transport'
      path: '/transport'
      fullPath: '/onboarding/transport'
      preLoaderRoute: typeof OnboardingTransportRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/provider': {
      id: '/onboarding/provider'
      path: '/provider'
      fullPath: '/onboarding/provider'
      preLoaderRoute: typeof OnboardingProviderRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/driver/settings': {
      id: '/driver/settings'
      path: '/settings'
      fullPath: '/driver/settings'
      preLoaderRoute: typeof DriverSettingsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/requests': {
      id: '/driver/requests'
      path: '/requests'
      fullPath: '/driver/requests'
      preLoaderRoute: typeof DriverRequestsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/dashboard/sos': {
      id: '/dashboard/sos'
      path: '/sos'
      fullPath: '/dashboard/sos'
      preLoaderRoute: typeof DashboardSosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ride': {
      id: '/dashboard/ride'
      path: '/ride'
      fullPath: '/dashboard/ride'
      preLoaderRoute: typeof DashboardRideRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/food': {
      id: '/dashboard/food'
      path: '/food'
      fullPath: '/dashboard/food'
      preLoaderRoute: typeof DashboardFoodRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emergency': {
      id: '/dashboard/emergency'
      path: '/emergency'
      fullPath: '/dashboard/emergency'
      preLoaderRoute: typeof DashboardEmergencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/food/': {
      id: '/dashboard/food/'
      path: '/'
      fullPath: '/dashboard/food/'
      preLoaderRoute: typeof DashboardFoodIndexRouteImport
      parentRoute: typeof DashboardFoodRoute
    }
    '/dashboard/food/track': {
      id: '/dashboard/food/track'
      path: '/track'
      fullPath: '/dashboard/food/track'
      preLoaderRoute: typeof DashboardFoodTrackRouteImport
      parentRoute: typeof DashboardFoodRoute
    }
    '/dashboard/food/checkout': {
      id: '/dashboard/food/checkout'
      path: '/checkout'
      fullPath: '/dashboard/food/checkout'
      preLoaderRoute: typeof DashboardFoodCheckoutRouteImport
      parentRoute: typeof DashboardFoodRoute
    }
    '/dashboard/food/$vendor': {
      id: '/dashboard/food/$vendor'
      path: '/$vendor'
      fullPath: '/dashboard/food/$vendor'
      preLoaderRoute: typeof DashboardFoodVendorRouteImport
      parentRoute: typeof DashboardFoodRoute
    }
  }
}

interface DashboardFoodRouteChildren {
  DashboardFoodVendorRoute: typeof DashboardFoodVendorRoute
  DashboardFoodCheckoutRoute: typeof DashboardFoodCheckoutRoute
  DashboardFoodTrackRoute: typeof DashboardFoodTrackRoute
  DashboardFoodIndexRoute: typeof DashboardFoodIndexRoute
}

const DashboardFoodRouteChildren: DashboardFoodRouteChildren = {
  DashboardFoodVendorRoute: DashboardFoodVendorRoute,
  DashboardFoodCheckoutRoute: DashboardFoodCheckoutRoute,
  DashboardFoodTrackRoute: DashboardFoodTrackRoute,
  DashboardFoodIndexRoute: DashboardFoodIndexRoute,
}

const DashboardFoodRouteWithChildren = DashboardFoodRoute._addFileChildren(
  DashboardFoodRouteChildren,
)

interface DashboardRouteChildren {
  DashboardEmergencyRoute: typeof DashboardEmergencyRoute
  DashboardFoodRoute: typeof DashboardFoodRouteWithChildren
  DashboardRideRoute: typeof DashboardRideRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSosRoute: typeof DashboardSosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEmergencyRoute: DashboardEmergencyRoute,
  DashboardFoodRoute: DashboardFoodRouteWithChildren,
  DashboardRideRoute: DashboardRideRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSosRoute: DashboardSosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DriverRouteChildren {
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverRequestsRoute: typeof DriverRequestsRoute
  DriverSettingsRoute: typeof DriverSettingsRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverRequestsRoute: DriverRequestsRoute,
  DriverSettingsRoute: DriverSettingsRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingProviderRoute: typeof OnboardingProviderRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  OnboardingTransportRoute: typeof OnboardingTransportRoute
  OnboardingUserRoute: typeof OnboardingUserRoute
  OnboardingVendorRoute: typeof OnboardingVendorRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingProviderRoute: OnboardingProviderRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  OnboardingTransportRoute: OnboardingTransportRoute,
  OnboardingUserRoute: OnboardingUserRoute,
  OnboardingVendorRoute: OnboardingVendorRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface ResponderRouteChildren {
  ResponderAlertsRoute: typeof ResponderAlertsRoute
  ResponderBroadcastRoute: typeof ResponderBroadcastRoute
  ResponderDirectoryRoute: typeof ResponderDirectoryRoute
  ResponderIndexRoute: typeof ResponderIndexRoute
}

const ResponderRouteChildren: ResponderRouteChildren = {
  ResponderAlertsRoute: ResponderAlertsRoute,
  ResponderBroadcastRoute: ResponderBroadcastRoute,
  ResponderDirectoryRoute: ResponderDirectoryRoute,
  ResponderIndexRoute: ResponderIndexRoute,
}

const ResponderRouteWithChildren = ResponderRoute._addFileChildren(
  ResponderRouteChildren,
)

interface VendorRouteChildren {
  VendorProductsRoute: typeof VendorProductsRoute
  VendorRatingsRoute: typeof VendorRatingsRoute
  VendorSalesRoute: typeof VendorSalesRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorStorefrontRoute: typeof VendorStorefrontRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorProductsRoute: VendorProductsRoute,
  VendorRatingsRoute: VendorRatingsRoute,
  VendorSalesRoute: VendorSalesRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorStorefrontRoute: VendorStorefrontRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  ResponderRoute: ResponderRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VendorRoute: VendorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
